name: Cache Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: prime-cache-1f498aa
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-1f498aa

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
