name: Cache Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create cache content
        run: |
          mkdir -p $HOME/.cache/mydeps
          echo "primed at $(date)" > $HOME/.cache/mydeps/primed.txt

      - name: Cache dependencies
        id: cache_deps               
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/mydeps
          key: cache-1f498aa         

      - name: prime-cache-1f498aa     
        run: echo "Cache hit: ${{ steps.cache_deps.outputs.cache-hit }}"
