name: Email Action Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 24f3001403@ds.study.iitm.ac.in
        run: echo "Hello, world!"
